-- Recommend SQLite Expert Personal, it's a good software.
-- These sql express tested in sqlite 3.7.9.

CREATE TABLE [DOWNLOAD_LINK] (
  [_ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  [DL_HEADER_ID] INTEGER NOT NULL, 
  [DL_LINK] TEXT,
  [DL_LOCAL_PATH] TEXT);


CREATE TABLE [FILM] (
  [_ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  [FM_DATE] TIMESTAMP NOT NULL DEFAULT (datetime(CURRENT_TIMESTAMP, 'localtime')), 
  [FM_DESC] TEXT);


CREATE TABLE [IMAGE] (
  [_ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  [IMG_HEADER_ID] INTEGER NOT NULL, 
  [IMG_NET_PATH] TEXT,
  [IMG_LOCAL_PATH] TEXT);


